### ISSUE TITLE
Code pattern steps unclear

### ISSUE THREAD

**Issue by timroster** [IBM/pulse-iot-wml-mobile-health#8]
The steps in this README and linked files seem to require additional actions to be performed by the user which are not documented. For example the `deploy.sh` script uses this command to log in:

```
cf login -u username -o org_name -s space_name
```

Which needs to be edited since the values are not parameterized and will vary from user to user. The instructions should mention these edits. Similarly for other assumed edits such as the host name in `manifest.yml`

The steps seem to require a user to understand what to fix and are not consistent in this way with other code pattern repositories ( see: https://github.com/IBM/spring-boot-microservices-on-kubernetes ).

**Comment by hovig** [comment]
this project is meant for developers with Intermediate level. if you don't know the very basic information, then this is not for you
