### ISSUE TITLE
Accuracy and trustworthiness of this solution

### ISSUE THREAD

**Issue by timroster** [IBM/pulse-iot-wml-mobile-health#9]
According to the abstract of a recently published peer-reviewed review article on the use of smartphone accelerometers [Smartphone accelerometers for the detection of heart rate](https://www.ncbi.nlm.nih.gov/pubmed/29161916) , there are some potential issues with the techniques described in this repository:
"Expert commentary: From the results of this review, the smartphone can be considered a powerful device able to accurately measure the resting heart rate, thanks to embedded accelerometer technology. However, lack of a shared standard in the acquisition protocol and analysis procedure, thus affecting user-collected data reliability, could limit clinical acceptability and prevent recommending this approach as a self-tracking tool in patients."

There is no information provided in the README regarding the scientific basis for the methodology used in the sensing application in any of the references, nor is there much information on the provenance of the code used.

Scanning some code source reveals several areas marked "TODO" such as line 802-803 in `public/js/audioprocessor.js` which has:
```
  * Performs a convolution on two arrays
  * TODO: documentation; we pulled this algorithm from StackOverflow—but where?
```

This solution could be clarified by providing more explicit references related to the methods and limitations in the Useful Links section. It may also need a general disclaimer at the top like: https://github.com/IBM/predictive-model-on-watson-ml/

**Comment by hovig** [comment]
The app states it:
![image](https://user-images.githubusercontent.com/5958327/40070918-0d75769e-5835-11e8-9cb5-e8c247fa0d8c.png)

You either enjoy the app, improve it and take it to whichever level you would like of building your app or try the app at least and see that I do mention that these are approximated measurements. The study in this project is beyond of the scope of a pattern or a repo. I'm sharing knowledge and not building an HHS or FDA or not sure what other org type of app.
